TRACE ---------------------------------------;
TRACE including 01_Main.qvs / Version 1.02;

// Change History
// 1.01, 04-Nov-2022, Möglichkeit zum Verfälschen von Werten vFalsifyFactor eingebaut
// 1.02, 10-Okt-2022
SET vBaseFolder = [lib://Igel:OneDrive/digipoint];
TRACE ⭐ vBaseFolder ist $(vBaseFolder);

SET ThousandSep='.';
SET DecimalSep=',';
SET MoneyThousandSep='.';
SET MoneyDecimalSep=',';
SET MoneyFormat='#.##0,00 €;-#.##0,00 €';
SET TimeFormat='hh:mm:ss';
SET DateFormat='DD.MM.YYYY';
SET TimestampFormat='DD.MM.YYYY hh:mm:ss[.fff]';
SET FirstWeekDay=0;
SET BrokenWeeks=0;
SET ReferenceDay=4;
SET FirstMonthOfYear=1;
SET CollationLocale='de-DE';
SET MonthNames='Jan;Feb;Mär;Apr;Mai;Jun;Jul;Aug;Sep;Okt;Nov;Dez';
SET LongMonthNames='Januar;Februar;März;April;Mai;Juni;Juli;August;September;Oktober;November;Dezember';
SET DayNames='Mo.;Di.;Mi.;Do.;Fr.;Sa.;So.';
SET LongDayNames='Montag;Dienstag;Mittwoch;Donnerstag;Freitag;Samstag;Sonntag';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';
SET CreateSearchIndexOnReload=1; 
SEARCH INCLUDE '*';
SEARCH EXCLUDE '%*';
SET DISABLE_INSIGHTS = ''; // '1' off, '' on

SET vFalsifyApps = `'Test Hotel [543]', 'Hotel - Der Kaiser [613]'`;
LET vFalsifyFactor = 0.347;

// Lege Felder, die "always one selected value" im UI angewählt haben, immer im Datenmodell vorhanden
// sind, selbst wenn das Script mit einem Fehler abbricht, werden sie hier schon einmal temporär angelegt und
// im Script 99_Exit.qvs wieder entfernt
SET vSingleValueFields = 'Toggle','Bericht','Datenarten','Betrieb';
FOR EACH vSingleValueField IN $(vSingleValueFields)
	[$(vSingleValueField)]: LOAD '' AS [$(vSingleValueField)] AUTOGENERATE(1);
NEXT vSingleValueField

// Tabelle, in die - wenn nötig - diverse Fehlermeldungen geladen werden
ERRORS: LOAD * INLINE [ErrorMsg];
