TRACE ---------------------------------------;
TRACE Including 50_Kalender.qvs / Version 1.1;
// Version Changes
// 1.01, Dual-Wert für Feld JahrMonat 
// 1.02, 20.10.2021, Feld "Monat" gefixed 
// 1.03, 10.11.2021, Vorjahr gefixed, so dass es Dual-Wert in JahrMonat korrekt nachzieht, neu: GMonat (Geschäftsmonat)
// 1.1, 30.11.2022, Neues Dual-Feld "Monat" eingeführt

// GJ_Beginn_Lookup:
// MAPPING 
// LOAD DISTINCT Betrieb_ID, gj_beginn RESIDENT BerichtZeilen;

LET vToggleMonatOptions = 'JahrMonat|Monat';
LET vToggleMonat = If(Len('$(vToggleMonat)'), vToggleMonat, 'JahrMonat');

Kalender:
LOAD DISTINCT
    %BetriebZeit
    ,Dual(
        Subfield('$(MonthNames)',';',Right(Zeit_ID, 2)) &' '& Mid(Zeit_ID, 3, 2)
        ,Zeit_ID
    ) /*..............................................*/      AS JahrMonat
    ,Dual(Subfield('$(MonthNames)',';',Right(Zeit_ID, 2))
        ,1 + Mod(Right(Zeit_ID,2) - GJ_Beginn, 12))           AS Monat
    ,Text(If(Len(Zeit_ID)=6,
      If(GJ_Beginn=1,
          Left(Zeit_ID,4),
          If(Num#(Right(Zeit_ID,2)) >= GJ_Beginn,
              Left(Zeit_ID,4) & '/' & (Num#(Left(Zeit_ID,4))+1),
              (Num#(Left(Zeit_ID,4))-1) & '/' & Left(Zeit_ID,4)
          )
      ),
      If(GJ_Beginn=1, 
      	Zeit_ID,
     	Zeit_ID & '/' & (Zeit_ID+1)   
      )
    ))  /*..............................................*/    AS Jahr
    ,1 + Mod(Ceil((Right(Zeit_ID,2) - GJ_Beginn+1)/3)+3, 4)   AS Quartal
    ,1 + Mod(Right(Zeit_ID,2) - GJ_Beginn, 12)                AS GMonat
    ,0  /*..............................................*/    AS Vorjahr;
LOAD DISTINCT
	%BetriebZeit, 
    Zeit_ID, 
    gj_beginn AS GJ_Beginn
    //ApplyMap('GJ_Beginn_Lookup', Betrieb_ID, '?') AS GJ_Beginn
RESIDENT 
	BerichtZeilen
WHERE
	Len(Zeit_ID) >= 4;

    
// Füge um 1, 2, 3 Jahre versetzte Einträge zum Kalender hinzu,
// um im Frontend auch Vorjahres Zahlen zu einem gegebenen Jahr anzeigen zu können    
FOR v = 1 TO 3    
    TRACE Füge Vorjahr -$(v) dem Kalender hinzu ...;

    CONCATENATE (Kalender)    
    LOAD
        %BetriebZeit
        // berechne Jahr+1 im Format von JahrMonat
        ,Dual(
            Subfield(JahrMonat,' ',1)  &' '& (Floor(JahrMonat/100)-1999)
            ,JahrMonat + $(v)00
        ) /*..............................................*/     AS JahrMonat
        ,Dual(Subfield(JahrMonat,' ',1), GMonat)                 AS Monat
        //(Left(JahrMonat,4) + $(v)) & Mid(JahrMonat, 5) AS JahrMonat,
        ,JahrMonat /*.......................................*/   AS stattJahrMonat
        ,(Left(Jahr,4) + $(v))
            & If(Len(Jahr)=4, '', '/' & (Right(Jahr,4) + $(v)))  AS Jahr
        ,Jahr /*.............................................*/  AS stattJahr
        ,-$(v) /*............................................*/  AS Vorjahr
        ,Quartal
        ,GMonat
    RESIDENT
        Kalender
    WHERE 
        Vorjahr = 0
        AND Exists(Zeit_ID, JahrMonat + $(v)00)  
        // JahrMonat + 100 ... zB aus 202011 wird 202111 (kein 'echtes' Datum, sondern 6-stellige Zahl)
    ;

NEXT v        


/*
LEFT JOIN (Kalender)
LOAD DISTINCT 
// JOIN ON
    JahrMonat,
// Add field
    Dual(
        Subfield(JahrMonat,' ',1), 
        Pick(Subfield(JahrMonat,' ',1),'Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez')
     ) AS Monat
RESIDENT
    Kalender
WHERE 
    Len(JahrMonat) = 6;
    */